# Workflow para compilar y desplegar un proyecto de Angular en GitHub Pages
name: Deploy Angular to GitHub Pages

on:
  # Se activa en cada push a la rama 'main'
  push:
    branches:
      - main
  
  # Permite ejecutar este workflow manualmente desde la pestaña Actions en GitHub
  workflow_dispatch:

# Permisos
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout
        uses: actions/checkout@v4

      - name: 2. Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 3. Install Dependencies
        run: npm ci

      - name: 4. Build Project
        run: npx ng build --base-href /${{ github.event.repository.name }}/

      - name: 5. Setup Pages
        uses: actions/configure-pages@v4

      - name: 6. Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # --- ¡ESTA ES LA CORRECCIÓN! ---
          # La ruta correcta para el builder de Angular v17+ es dist/PROJECT_NAME/browser/
          path: 'dist/LandingIndieNest/browser'

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
